export const AUTH_TOKENS = {
  USER_REPOSITORY: Symbol('USER_REPOSITORY'),
  PASSWORD_HASHER: Symbol('PASSWORD_HASHER'),
  TOKEN_VERIFIER: Symbol('TOKEN_VERIFIER'),
  OAUTH_VERIFIER: Symbol('OAUTH_VERIFIER'),
  REFRESH_TOKEN_REPOSITORY: Symbol('REFRESH_TOKEN_REPOSITORY'),
  HASH_SERVICE: Symbol('HASH_SERVICE'),
};
